### ISSUE TITLE
setup.js failed?

### ISSUE THREAD

**Issue by msqueeg** [CarpeTelam/cv3-developer-tools#1]
Hi @thisishuey ,
I'm getting an error saying that ./bin/setup.js failed. This is the more verbose log file:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'setup' ]
2 info using npm@2.15.5
3 info using node@v4.4.5
4 verbose run-script [ 'presetup', 'setup', 'postsetup' ]
5 info presetup cv3-dev@1.0.0
6 info setup cv3-dev@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info cv3-dev@1.0.0 Failed to exec setup script
9 verbose stack Error: cv3-dev@1.0.0 setup: `./bin/setup.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid cv3-dev@1.0.0
11 verbose cwd C:\etc\dev\cv3-developer-tools
12 error Windows_NT 10.0.10586
13 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "setup"
14 error node v4.4.5
15 error npm  v2.15.5
16 error code ELIFECYCLE
17 error cv3-dev@1.0.0 setup: `./bin/setup.js`
17 error Exit status 1
18 error Failed at the cv3-dev@1.0.0 setup script './bin/setup.js'.
18 error This is most likely a problem with the cv3-dev package,
18 error not with npm itself.

the install command ran clean. I'm running Windows 10 and the versions of node and npm are listed above. I'm going to try creating the json files by hand and then continuing on with setting on an environment. I'm not sure why it failed.

**Comment by msqueeg** [comment]
@thisishuey  - the problem is the preceding "." in the "./bin/setup.js" Windows will choke on that. But the dot slash syntax doesn't seem to cause problems inside the setup.js or extract.js files themselves, just with the run command.

**Comment by thisishuey** [comment]
Oh, interesting, I'm all Mac, so I haven't tested it on Windows at all.

Does that mean you were able to get it to work though? If you want to create a Pull Request, I can check out the fix on Mac and if all looks good, merge it in.

Thanks!

**Comment by msqueeg** [comment]
I was able to get it to work as far as I've tested it. Haven't tried pushing any modifications up to CV3.  I modified the commands inside the scripts braces following the example in here: https://shapeshed.com/writing-cross-platform-node/ I'll submit a pull request this evening when I get home from work.

**Comment by thisishuey** [comment]
I've gone ahead and merged this, thanks for the fix!
